server {
    listen 80;
    server_name portal.vutheanh.id.vn;

    location / {
        root /usr/share/nginx/html/site1;
        index index.html;
    }

    location /api/ {
        proxy_pass http://nodered_vutheanh:1880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name sec.vutheanh.id.vn;

    location / {
        root /usr/share/nginx/html/site2;
        index index.html;
    }
}
